- name: "Import jenkins configuration"
  hosts: jenkins
  become: true

  vars:
    jenkins_home: "/var/lib/jenkins"
  
  tasks:
    - name: Copy configuration
      copy:
        src: dev.yml
        dest: "{{ jenkins_home }}/jenkins.yaml"
        owner: jenkins
        group: jenkins

    - name: restart jenkins
      service: name=jenkins state=restarted
        
