- hosts: jenkins
  become: true

  pre_tasks:
    - name: Install latest curl
      ansible.builtin.dnf:
        name: curl
        state: present
        allowerasing: true
  vars:
    java_packages:
      -  java-17-amazon-corretto-headless
    jenkins_repo_key_url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
    jenkins_repo_url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
    jenkins_plugins:
      - name: amazon-ecr
      - name: ant
      - name: antisamy-markup-formatter
      - name: apache-httpcomponents-client-4-api
      - name: authentication-tokens
      - name: aws-credentials
      - name: aws-java-sdk
      - name: aws-java-sdk-cloudformation
      - name: aws-java-sdk-codebuild
      - name: aws-java-sdk-ec2
      - name: aws-java-sdk-ecr
      - name: aws-java-sdk-ecs
      - name: aws-java-sdk-efs
      - name: aws-java-sdk-elasticbeanstalk
      - name: aws-java-sdk-iam
      - name: aws-java-sdk-logs
      - name: aws-java-sdk-minimal
      - name: aws-java-sdk-sns
      - name: aws-java-sdk-sqs
      - name: aws-java-sdk-ssm
      - name: blueocean
      - name: blueocean-bitbucket-pipeline
      - name: blueocean-commons
      - name: blueocean-config
      - name: blueocean-core-js
      - name: blueocean-dashboard
      - name: blueocean-display-url
      - name: blueocean-events
      - name: blueocean-git-pipeline
      - name: blueocean-github-pipeline
      - name: blueocean-i18n
      - name: blueocean-jwt
      - name: blueocean-personalization
      - name: blueocean-pipeline-api-impl
      - name: blueocean-pipeline-editor
      - name: blueocean-pipeline-scm-api
      - name: blueocean-rest
      - name: blueocean-rest-impl
      - name: blueocean-web
      - name: bootstrap5-api
      - name: bouncycastle-api
      - name: branch-api
      - name: build-timeout
      - name: build-user-vars-plugin
      - name: caffeine-api
      - name: checks-api
      - name: cloudbees-bitbucket-branch-source
      - name: cloudbees-folder
      - name: command-launcher
      - name: commons-lang3-api
      - name: commons-text-api
      - name: configuration-as-code        
      - name: config-file-provider        
      - name: credentials
      - name: credentials-binding
      - name: dark-theme
      - name: data-tables-api
      - name: display-url-api
      - name: docker-commons
      - name: docker-workflow
      - name: durable-task
      - name: echarts-api
      - name: email-ext
      - name: extended-read-permission
      - name: favorite
      - name: font-awesome-api
      - name: git
      - name: git-client
      - name: git-server
      - name: github
      - name: github-api
      - name: github-branch-source
      - name: github-oauth
      - name: gradle
      - name: handy-uri-templates-2-api
      - name: htmlpublisher
      - name: instance-identity
      - name: ionicons-api
      - name: jackson2-api
      - name: jakarta-activation-api
      - name: jakarta-mail-api
      - name: javax-activation-api
      - name: javax-mail-api
      - name: jaxb
      - name: jdk-tool
      - name: jenkins-design-language
      - name: jjwt-api
      - name: job-dsl        
      - name: jquery3-api
      - name: jsch
      - name: junit
      - name: ldap
      - name: lockable-resources
      - name: mailer
      - name: mapdb-api
      - name: matrix-auth
      - name: matrix-project
      - name: mina-sshd-api-common
      - name: mina-sshd-api-core
      - name: okhttp-api
      - name: pam-auth
      - name: pipeline-aws
      - name: pipeline-build-step
      - name: pipeline-github-lib
      - name: pipeline-graph-analysis
      - name: pipeline-input-step
      - name: pipeline-milestone-step
      - name: pipeline-model-api
      - name: pipeline-model-definition
      - name: pipeline-model-extensions
      - name: pipeline-multibranch-defaults
      - name: pipeline-rest-api
      - name: pipeline-stage-step
      - name: pipeline-stage-tags-metadata
      - name: pipeline-stage-view
      - name: pipeline-timeline
      - name: plain-credentials
      - name: plugin-util-api
      - name: pubsub-light
      - name: resource-disposer
      - name: scm-api
      - name: script-security
      - name: slack
      - name: snakeyaml-api
      - name: sse-gateway
      - name: ssh-credentials
      - name: ssh-slaves
      - name: sshd
      - name: structs
      - name: subversion
      - name: theme-manager
      - name: timestamper
      - name: token-macro
      - name: trilead-api
      - name: uno-choice
      - name: variant
      - name: workflow-aggregator
      - name: workflow-api
      - name: workflow-basic-steps
      - name: workflow-cps
      - name: workflow-durable-task-step
      - name: workflow-job
      - name: workflow-multibranch
      - name: workflow-scm-step
      - name: workflow-step-api
      - name: workflow-support
      - name: ws-cleanup      
    jenkins_plugins_install_dependencies: true
    jenkins_plugins_state: present
    
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
